import AppContainer from "./container";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return <AppContainer>{children}</AppContainer>;
}
